### ISSUE TITLE
Problem with `opt ?+`

### ISSUE THREAD

**Issue by laoo** [pfusik/upkr6502#1]
usage of `opt ?+` directive prevents the subsequent declaration of local areas in mads.

The code
```
    org $2000

    jmp loc.label


unupkr_mul      equ 0
unupkr_probs    equ $400
unupkr_zp       equ $80
    icl	'unupkr.asx'
    opt ?-


.local loc

label rts

.endl
```
does not assemble in mads. Presence of `opt ?-` does not change anything. Only removing `opt ?+` from inside unupkr.asx` helps.

**Comment by pfusik** [comment]
upkr6502 uses local labels, not mads-default temporary labels.

If `opt ?-` doesn't undo `opt ?+`, isn't this a bug in mads, @tebe6502 ?

**Comment by laoo** [comment]
It seems that TeBe fixed the issue in mads in latest commit: https://github.com/tebe6502/Mad-Assembler/commit/51596d4fc9a88d52ade647f89e3d5de1b5fc41ee
